'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MFSAadharConfirmation

    '''<summary>
    '''frmAadhar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmAadhar As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''USER_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents USER_ID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''PASSWORD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PASSWORD As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''SESSION_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SESSION_ID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''PAN_PEKRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PAN_PEKRN As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''RETN_URL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RETN_URL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''REQUEST_TYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REQUEST_TYPE As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''AADHAAR_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AADHAAR_NAME As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''DOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOB As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''GENDER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GENDER As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''MOBILE_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MOBILE_NO As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''EMAIL_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EMAIL_ID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''URL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents URL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''reqObj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqObj As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''MOBILENO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MOBILENO As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnXML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnXML As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''dverror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dverror As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spnloadmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spnloadmsg As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
